projectPHP/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/* Route::get('/panier', 'PanierController@index')->name('panier.index');
Route::post('/panier', 'PanierController@store')->name('panier.store');
 */

Route::get('billets/choose', function()
{
    return view('billets.choose');
})->name('choose');

Route::post('billets/valider', 'BilletsController@valider')->name('billets.valider');

Route::post('billets/choose', 'BilletsController@choose')->name('billets.choose');
Route::put('billets/{id}', 'BilletsController@update')->name('billet');
Route::get('billets/accueil', 'BilletsController@accueil')->name('billets.index');
Route::resource('/billets', 'BilletsController');

Route::post('coupon/create', ['uses' => 'CouponsController@save']);

Route::post('panier/{id}', 'CartController@update')->name('panier.update');

Route::delete('/coupon', 'CouponsController@supprimer')->name('coupon.delete');
Route::delete('/coupon/{id}', 'CouponsController@retirer')->name('coupon.retirer');
Route::post('/coupon', 'CouponsController@store')->name('coupon.store');
Route::resource('/coupon', 'CouponsController');

Route::get('/delete', function()
{
    session()->flush();
});

Route::get('panier', 'CartController@index')->name('panier.index');
Route::post('add', 'CartController@add');
Route::post('destroy/{id}', 'CartController@destroy')->name('panier.destroy');
/* Route::post('destroy', 'CartController@destroy')->name('panier.destroy'); */
Route::post('destroy', 'CartController@supprimer')->name('panier.supprimer');

Auth::routes();

projectPHP/app/Billet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Coupon;

class Billet extends Model
{
    public function coupons(){
        return $this->hasMany(\App\Coupon::class);
    }
}

projectPHP/app/Http/Controllers/BilletsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Billet;
use App\Models\Match;
use DB;

class BilletsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $billets = Billet::all();
        return view('billets.index', ['billets' => $billets]);
    }

    public function choose(Request $r)
    {
        if(session()->has('matchExiste') && $r->supprimer)
        {
            session()->forget('matchExiste');
        }
        $matchs = Match::where('dateDebutM', $r->dateMatch)->where('idCourt', $r->court)->first();
        if($matchs)
        {
            session()->put('matchExiste', [
                'dateMatch' => $r->dateMatch,
                'court' => $r->court,
            ]);
            return redirect()->route('billets.index');
        } else {
            return redirect()->route('choose')->withErrors('Pas de date sélectionnée');
        }
    }

    public function valider(request $r)
    {
        $total = $r->total;
        return view('billets.valider', ['total' => $total]);
    }

    public function accueil(Request $r)
    {
        $match = Match::where('dateDebutM', $r->dateMatch)->get();
        if(!$match)
        {
            return redirect()->route('billets.index');
        }
        return redirect()->route('billets.index');
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('billets.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'quantite' => 'required',
            'prix'     => 'required'
        ]);

        if(!$request->typeMatch || $request->prix<=0 || $request->quantite<0)
        {
            return redirect()->route('billets.create')->withErrors('Erreur de saisie. Veuillez réessayer.');
        }

        $billet = new Billet();
        $billet->typeMatch = $request->typeMatch;
        $billet->prix = $request->prix;
        $billet->quantite = $request->quantite;
        $billet->save();
        return redirect()->route('home')->withSuccess('Billet ajouté avec succès.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $billet = Billet::findOrFail($id);
        return view('billets.edit', ['billet' => $billet, 'id' => $id]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'quantite' => 'required',
            'prix'     => 'required'
        ]);
        
        $billet = Billet::findOrFail($id);
        if($request->quantite>=0 && $request->prix>=0)
        {
        $billet->quantite = $request->get('quantite');
        $billet->prix = Str::replaceFirst(',', '.',$request->get('prix'));
        $billet->save();
        return redirect()->route('home')->with('success', 'Billet modifié avec succès !');
        }
        else
        {
            return redirect()->route('billets.edit', $billet)->withErrors('Valeurs invalides.');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $billet = Billet::where('id', $id)->first();
        $billet->delete();
        return redirect()->route('home')->withSuccess('Billet supprimé avec succès');
    }
}

projectPHP/resources/views/billets/accueil.blade.php
fesirfbseirfbseouyhb

projectPHP/resources/views/billets/choose.blade.php
@extends('layouts.app')

@section('head')
<style>
html
{
background-size:cover;
}
</style>
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-7">
            <div class="card">
                <div class="card-header" style="text-transform: uppercase; background: white; color: #384d9b; font-weight: bold;">Achetez vos billets
                    <a class="float-right" href="{{ URL::to('/') }}">Retour</a>
                </div>
                <div class="card-body bg-white" style="font-size: 1.5vh;">
                @if (session()->has('success'))
                    <div class="alert alert-success">
                            {{ session()->get('success') }}
                    </div>
                    @endif
                @if (count($errors)>0)
                    <div class="alert alert-danger">
                            @foreach ($errors->all() as $error)
                                {{$error}}
                            @endforeach
                    </div>
                @endif
                    <form method="post" action="{{route('billets.choose')}}">
                        @csrf
                        <div class="form-group">
                        <label for="dateMatch">Choisissez la date du match</label>
                        <input class="form-control" type="date" name="dateMatch">
                        </div>
                        <div class="form-group">
                        <label for="court">Pour quel court ?</label>
                        <select name="court" class="form-control">
                            <option value="0">Court central </option>
                            <option value="1">Court annexe 1</option>
                            <option value="2">Court annexe 2</option>
                            <option value="3">Court annexe 3</option>
                        </select>
                        </div>
                        <input type="submit" class="form-control btn btn-success mt-4" value="Recherchez les billets disponibles" style="font-size: 1.8vh;">
                    </form>
                    </div>
{{--                 <a href="{{url::('billets.accueil')}}">Aller</a>
 --}}            </div>
        </div>
    </div>
</div>
@endsection

projectPHP/resources/views/billets/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Panel d'administration
                <a class="float-right" href="{{ URL::to('/') }}">Accueil</a></div>
                <div class="card-body">
                    @if (session()->has('success'))
                    <div class="alert alert-success">
                            {{ session()->get('success') }}
                    </div>
                    @endif
                @if (count($errors)>0)
                    <div class="alert alert-danger">
                            @foreach ($errors->all() as $error)
                                {{$error}}
                            @endforeach
                    </div>
                @endif
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <h3>Gestion des billets</h3>
                    <hr>
                    <form method="post" action="{{route('billets.store')}}">
                    @csrf
                    <label class="mt-2" for="typeMatch">Type de billet</label>
                    <input class="form-control" placeholder="" id="typeMatch" name="typeMatch">

                    <label class="mt-2" for="prix">Prix du billet</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">€</div>
                        </div>
                    <input class="form-control" value="" id="prix "name="prix">
                    </div>
                    <label class="mt-2" for="quantite">Quantité</label>
                    <input class="form-control" value="" id="quantite" name="quantite">

                    <input class="float-right btn btn-success form-control w-75 mt-4" type="submit" value="Créer le billet">
                    <a class="float-right btn btn-danger form-control w-25 mt-4" href="{{ URL::to('home') }}">Annuler</a>

                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

projectPHP/resources/views/billets/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Panel d'administration
                <a class="float-right" href="{{ URL::to('/') }}">Accueil</a></div>
                <div class="card-body">
                    @if (session()->has('success'))
                    <div class="alert alert-success">
                            {{ session()->get('success') }}
                    </div>
                    @endif
                @if (count($errors)>0)
                    <div class="alert alert-danger">
                            @foreach ($errors->all() as $error)
                                {{$error}}
                            @endforeach
                    </div>
                @endif
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <h3>Gestion des billets</h3>
                    <hr>
                    <form method="post" action="{{action('BilletsController@update', $id)}}">
                    @csrf
                    @method('PATCH')
                    <label class="mt-2" for="typeMatch">Type de billet</label>
                    <input class="form-control" placeholder="{{$billet->typeMatch}}" id="typeMatch" name="typeMatch" readonly>

                    <label class="mt-2" for="prix">Prix du billet</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">€</div>
                        </div>
                    <input class="form-control" value="{{$billet->prix}}" id="prix "name="prix">
                    </div>
                    <label class="mt-2" for="quantite">Quantité</label>
                    <input class="form-control" value="{{$billet->quantite}}" id="quantite" name="quantite">

                    <input class="float-right btn btn-success form-control w-75 mt-4" type="submit" value="Éditer le billet">
                    <a class="float-right btn btn-danger form-control w-25 mt-4" href="{{ URL::to('home') }}">Annuler</a>

                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

projectPHP/resources/views/billets/index.blade.php
@extends('layouts.app')

@section('content')
@php
    set_time_limit(0);
@endphp
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header" style="text-transform: uppercase; background: white; color: #384d9b; font-weight: bold;">Achetez vos billets
                <a class="float-right" href="{{ route('choose') }}">Retour</a></div>
                @if (session()->has('success'))
                    <div class="alert alert-success">
                            {{ session()->get('success') }}
                    </div>
                    @endif
                @if (count($errors)>0)
                    <div class="alert alert-danger">
                            @foreach ($errors->all() as $error)
                                {{$error}}
                            @endforeach
                    </div>
                @endif

                @php
                $check = false;
                foreach (Cart::content() as $item) {
                    if ($item->name == "Licenciés") {
                        $check = true;
                    } else {
                        $check = false;
                    }
                }
                echo $check;
                @endphp

                {{-- <form action="{{url('add')}}" method="post">
                    @csrf
                    <input type="hidden" value="{{$var[0]['id']}}" name="id">
                    <input type="hidden" value="{{$var[0]['typeMatch']}}" name="typeMatch">
                    <input type="number" value="1" name="quantite">
                    <input type="hidden" value="{{$var[0]['prix']}}" name="prix">
                    <input type="submit" value="Ajouter"><br>
                </form> --}}
                <img src="{{asset('images/billetsbg.jpg')}}" style="height: 50vh;">
                <div class="card-body bg-light" style="background: #384d9b; color:black;font-size: 1.8vh; opacity: 0.95;">
                <h4 class="text-center">Billets pour la journée {{session()->get('matchExiste')['dateMatch']}}</h4>
                <h5 class="text-center">
                    Court 
                    @switch(session()->get('matchExiste')['court'])
                        @case(0)
                            {{"central"}}
                            @break
                        @case(1)
                            {{"annexe 1"}}
                            @break
                        @case(2)
                            {{"annexe 2"}}
                            @break;
                        @case(3)
                            {{"annexe 3"}}
                            @break;
                        @default
                            
                    @endswitch
                </h5>
                    <hr>
                        @foreach ($billets as $billet)
                            @if ($billet->quantite>0)
                            @if ($billet->typeMatch=="Licenciés" && !$check || $billet->typeMatch!="Licenciés")
                            <div class="d-flex justify-content-between">
                                <h3>{{$billet->typeMatch}}
                                <p style="font-size: 1.5vh; font-weight: 400;">Quantité restante: {{$billet->quantite}}.</p>
                                </h3>
                                <form class="column" action="{{url('add')}}" method="post">
                                @csrf
                                <div class="d-flex align-self-center">
                                    <input type="hidden" value="{{$billet->id}}" name="id">
                                    <input type="hidden" value="{{$billet->typeMatch}}" name="typeMatch">
                                    <input type="hidden" value="{{$billet->prix}}" name="prix">
                                    <select class="form-control mr-2" name="place">
                                        <option value="0">Placement libre (0€)</option>
                                        <option value="15">Niveaux 1 et 2 (+15€)</option>
                                        <option value="30">Niveaux 3 (+30€)</option>
                                    </select>
                                    @if ($billet->typeMatch == "Licenciés")
                                    <input type="number" class="form-control text-center mr-2"  style="width: 6vh;" value="1" name="quantite" readonly>
                                    @else
                                    <input type="number" class="form-control text-center mr-2" value="1" name="quantite" style="width: 6vh;">
                                    @endif
                                    <button type="submit" class="btn btn-success">
                                        <i class="fas fa-check"></i>
                                    </button>
                                </div>
                                </form>
                            </div>
                            <hr>
                            @else
                            <div class="d-flex justify-content-between" style="opacity: 0.5;">
                                <h3>{{$billet->typeMatch}} (déjà dans votre panier)
                                <p style="font-size: 1.5vh; font-weight: 400;">Déjà acheté</p>
                                <p style="font-size: 1.5vh; font-weight: 400; line-height:0">Du Samedi 16/05/2020 au Samedi 23/05/2020</p>
                                </h3>
                                <form class="column" method="post">
                                @csrf
                                <div class="d-flex align-self-center">
                                    <input type="number" class="form-control text-center mr-2" value="0" name="quantite" style="width: 6vh;" readonly>
                                    <button type="submit" class="btn btn-danger form-control">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                                </form>
                            </div>
                            <hr>
                            @endif
                            @else
                            <div class="d-flex justify-content-between" style="opacity: 0.5;">
                                <h3>{{$billet->typeMatch}}
                                <p style="font-size: 1.5vh; font-weight: 400;">Quantité insuffisante.</p>
                                <p style="font-size: 1.5vh; font-weight: 400; line-height:0">Du Samedi 16/05/2020 au Samedi 23/05/2020</p>
                                </h3>
                                <form class="column" action="" method="post">
                                @csrf
                                <div class="d-flex align-self-center">
                                    <input type="number" class="form-control text-center mr-2" value="0" name="quantite" style="width: 6vh;" readonly>
                                    <button type="submit" class="btn btn-danger form-control">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                                </form>
                            </div>
                            <hr>
                            @endif
                            
                        @endforeach

                    <a class="btn btn-primary form-control" style="font-size: 2vh;" href="{{ url('panier') }}">
                        <i class="fas fa-shopping-cart"></i>{{ __(' Panier') }}
                        <span>({{Cart::count()}})</span>
                    </a>                </div>
            </div>
        </div>
    </div>
</div>
@endsection

projectPHP/resources/views/billets/valider.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Récapitulatif d'achat
                <a class="float-right" href="{{ URL::previous() }}">Retour</a></div>
                <div class="card-body">
                    @if (session()->has('success'))
                    <div class="alert alert-success">
                            {{ session()->get('success') }}
                    </div>
                    @endif
                @if (count($errors)>0)
                    <div class="alert alert-danger">
                            @foreach ($errors->all() as $error)
                                {{$error}}
                            @endforeach
                    </div>
                @endif
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <h3>Informations personnelles</h3>
                    <form method="post" action="{{route('billets.store')}}">
                    @csrf
                    <label class="mt-2" for="nom">Nom *</label>
                    <input class="form-control form-control-lg" placeholder="Ex.: Dupont" id="nom" name="nom">

                    <label class="mt-2" for="prenom">Prénom *</label>
                    <input class="form-control form-control-lg" placeholder="Ex.: Christian" id="prenom" name="prenom">

                    <label class="mt-2" for="prenom">Date de naissance *</label>
                    <input type="date" class="form-control form-control-lg" placeholder="Ex.: 06/11/2000" id="dateNaissance" name="dateNaissance">

                    <label class="mt-2" for="prenom">Adresse *</label>
                    <input class="form-control form-control-lg" placeholder="Ex.: 20 Rue des Lilas" id="adresse" name="adresse">
                </form>
                <br><hr>
                <form method="post" action="{{-- {{route('billets.store')}} --}}">
                    @csrf
                <h3>Paiement</h3><br>
                <input class="form-control form-control-lg" placeholder="Numéro carte" id="numCarte" name="numCarte"><br>
                <input class="form-control form-control-lg" placeholder="Nom possesseur de la carte" id="nomCarte" name="nomCarte"><br>
                <div class="d-flex">
                <input class="form-control form-control-lg w-75 mr-2" placeholder="Date d'expiration (jj/mm/aaaa)" id="dateExpiration" name="dateExpiration">
                <input class="form-control form-control-lg w-25 ml-2" placeholder="CVV" id="cvv" name="cvv">
            </div><br>
            <div class="d-flex justify-content-between align-items-center">
            <img style="width:20%;cursor:pointer;" class="img-fluid" src="{{asset('images/paypal.jpg')}}">
            <img style="width:15%; height:15%; cursor:pointer;" class="img-fluid" src="{{asset('images/visa.jpg')}}">
            <input type="submit" class="btn btn-success btn-lg form-control w-50" value="Valider l'achat">
            </div>
        </div>
            </div>
        </div>
        <div class="card row ml-2 h-50">
            <div class="card-header">Vos billets</div>
            <div class="card-body">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Billet(s)</th>
                    <th scope="col">Quantité</th>
                  </tr>
                </thead>
                <tbody>
                    @foreach (Cart::content() as $item)
                    <tr>
                        <td>{{$item->name}}</td>
                        <td class="text-center">x{{$item->qty}}</td>
                      </tr>
                    @endforeach
                    <tr>
                        <th><h4>Total</h4></th>
                        <td class="text-center"><h4>{{$total}}€</h4></td>
                    </tr>
                </tbody>
              </table>
            </div>
        </div>
    </div>
</div>
@endsection