projectPHP/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/* Route::get('/panier', 'PanierController@index')->name('panier.index');
Route::post('/panier', 'PanierController@store')->name('panier.store');
 */

Route::get('billets/choose', function()
{
    return view('billets.choose');
})->name('choose');

Route::post('billets/valider', 'BilletsController@valider')->name('billets.valider');

Route::post('billets/choose', 'BilletsController@choose')->name('billets.choose');
Route::put('billets/{id}', 'BilletsController@update')->name('billet');
Route::get('billets/accueil', 'BilletsController@accueil')->name('billets.index');
Route::resource('/billets', 'BilletsController');

Route::post('coupon/create', ['uses' => 'CouponsController@save']);

Route::post('panier/{id}', 'CartController@update')->name('panier.update');

Route::delete('/coupon', 'CouponsController@supprimer')->name('coupon.delete');
Route::delete('/coupon/{id}', 'CouponsController@retirer')->name('coupon.retirer');
Route::post('/coupon', 'CouponsController@store')->name('coupon.store');
Route::resource('/coupon', 'CouponsController');

Route::get('/delete', function()
{
    session()->flush();
});

Route::get('panier', 'CartController@index')->name('panier.index');
Route::post('add', 'CartController@add');
Route::post('destroy/{id}', 'CartController@destroy')->name('panier.destroy');
/* Route::post('destroy', 'CartController@destroy')->name('panier.destroy'); */
Route::post('destroy', 'CartController@supprimer')->name('panier.supprimer');

Auth::routes();

projectPHP/resources/views/home.blade.php
@extends('layouts.app')


@section('head')
<style>
html
{
background-size:cover;
}
</style>
@endsection


@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Panel d'administration
                <a class="float-right" href="{{ URL::to('/') }}">Accueil</a></div>
                <div class="card-body">
                    @if (session()->has('success'))
                    <div class="alert alert-success">
                            {{ session()->get('success') }}
                    </div>
                    @endif
                @if (count($errors)>0)
                    <div class="alert alert-danger">
                            @foreach ($errors->all() as $error)
                                {{$error}}
                            @endforeach
                    </div>
                @endif
                    <h3 class="mb-4">Gestion des billets</h3>
                    <table class="table table-hover table-bordered">
                        <thead>
                          <tr class="text-center">
                            <th>Nom du billet</th>
                            <th>Prix</th>
                            <th>Quantité</th>
                            <th>Éditer</th>
                            <th>Supprimer</th>
                          </tr>
                        </thead>

                        <tbody>
                            @foreach ($billets as $billet)
                            <tr class="text-center">
                                <td class="align-middle">{{$billet->typeMatch}}</td>
                                <td class="align-middle">{{$billet->prix}}€
                                </td>
                                    @if ($billet->quantite>0)
                                    <td class="align-middle">
                                        {{$billet->quantite}}
                                    </td>
                                    @else
                                    <td class="align-middle text-danger">
                                        {{$billet->quantite}}
                                    </td>
                                    @endif
                                   
                                </td>
                                <td class="align-middle">
                                    <form action="{{route('billets.edit', $billet) }}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-warning btn-sm m-1">
                                           <i class="far fa-edit"></i>
                                        </button>         
                                    </form>
                                </td>
                                <td class="align-middle">
                                    <form action="{{URL::route('billets.destroy', $billet->id)}}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button onclick="return confirm('Voulez-vous vraiment supprimer cette réduction ?');" type="submit" class="btn btn-danger btn-sm m-1">
                                           <i class="fas fa-times"></i>
                                        </button>         
                                    </form>
                                </td>
                            <tr>
                            @endforeach
                        </tbody>
                      </table>
                      <form class="mb-5" action="{{route('billets.create')}}" method="GET">
                        @csrf
                        <button type="submit" class="btn btn-primary float-right">
                            Nouveau billet
                        </button>
                    </form>

                    <h3 class="mb-4 mt-4">Gestion des codes de réduction</h3>
                    <table class="table table-hover table-bordered">
                        <thead>
                          <tr class="text-center">
                            <th>Code</th>
                            <th>Billet concerné</th>
                            <th>Réduction</th>
                            <th>Quantité</th>
                            <th>Éditer</th>
                            <th>Supprimer</th>
                          </tr>
                        </thead>

                        <tbody>
                            @foreach ($coupons as $coupon)
                            <tr class="text-center">
                                <td class="align-middle">{{$coupon->code}}</td>
                                <td class="align-middle">{{$coupon->getBillet()->typeMatch}}</td>
                                <td class="align-middle">{{$coupon->reduction}}%
                                </td>
                                    @if ($coupon->quantite>0)
                                    <td class="align-middle">
                                        {{$coupon->quantite}}
                                    </td>
                                    @else
                                    <td class="align-middle text-danger">
                                        {{$coupon->quantite}}
                                    </td>
                                    @endif
                                   
                                </td>
                                <td class="align-middle">
                                    <form action="{{route('coupon.edit', $coupon) }}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-warning btn-sm m-1">
                                           <i class="far fa-edit"></i>
                                        </button>         
                                    </form>
                                </td>
                                <td class="align-middle">
                                    <form action="{{URL::route('coupon.retirer', $coupon->id)}}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button onclick="return confirm('Voulez-vous vraiment supprimer cette réduction ?');" type="submit" class="btn btn-danger btn-sm m-1">
                                           <i class="fas fa-times"></i>
                                        </button>         
                                    </form>
                                </td>
                            <tr>
                            @endforeach
                        </tbody>
                      </table>
                      <form action="{{route('coupon.create')}}" method="GET">
                        @csrf
                        <button type="submit" class="btn btn-primary float-right">
                           Ajouter une réduction
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

projectPHP/resources/views/panier.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Gestion du panier
                <a class="float-right" href="{{ URL::to('/') }}">Accueil</a></div>
                <div class="card-body">
                @if (session()->has('success'))
                    <div class="alert alert-success">
                            {{ session()->get('success') }}
                    </div>
                @endif
                @if (session()->has('warning'))
                    <div class="alert alert-warning">
                            {{ session()->get('warning') }}
                    </div>
                @endif
                @if (count($errors)>0)
                    <div class="alert alert-danger">
                            @foreach ($errors->all() as $error)
                                {{$error}}
                            @endforeach
                    </div>
                @endif
                <h4>Votre panier ({{Cart::count()}})</h4><br>
                    @if (Cart::count()>0)
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col"><i class="fas fa-ticket-alt"></i> Billet</th>
                            <th scope="col">Quantité</th>
                            <th class="text-center"scope="col">Prix</th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach (Cart::content() as $item)
                            <tr>
                            <td><div class="d-flex">
                                <h5>{{$item->name}}</h5>
                                <form action="{{URL::route('panier.destroy', array('id' => $item->rowId))}}" method="post">
                                    @csrf
                                    <button type="submit" class="btn btn-sm text-danger">
                                        Supprimer
                                    </button>
                                </form>
                                </div>
                                @if ($item->name == 'Licenciés')
                                <div class="d-flex">
                                    <form action="{{route('coupon.store')}}" method="post">
                                    @csrf
                                    <div class="d-flex">
                                    <input placeholder="Code licencié" name="code" id="code" class="form-control form-control-sm mr-2 mb-3" type="text">
                                    <input type="hidden" value="{{$item->qty}}" name="quantite">
                                    <input type="hidden" value="{{$item->id}}" name="idBillet">
                                    <button type="submit" class="form-control form-control-sm btn-sm btn btn-primary w-25">
                                      <i class="fas fa-check"></i>
                                    </button>
                                    </div>
                                    </form>
                               </div>
                                @else
                                <div class="d-flex">
                                <br>
                                <form action="{{route('coupon.store')}}" method="post">
                                @csrf
                                <div class="d-flex">
                                <input placeholder="Code promo ?" name="code" id="code" class="form-control form-control-sm mr-2" type="text">
                                <input type="hidden" value="{{$item->qty}}" name="quantite">
                                <input type="hidden" value="{{$item->id}}" name="idBillet">
                                <button type="submit" class="form-control form-control-sm btn-sm btn btn-primary w-25">
                                  <i class="fas fa-check"></i>
                                </button>
                                </div>
                                </form>
                           </div>
                            </td>
                            @endif
                        <td class="align-middle">
                            <form action="{{URL::route('panier.update', array('id' => $item->rowId))}}" method="post">
                                @csrf
                                <div class="d-flex">
                                @if($item->name!="Licenciés")
                                <input class="text-center form-control form-control-sm w-25 mr-2" name="quantite" id="quantite" type="number" value="{{$item->qty}}">
                                <button class="btn btn-secondary btn-sm" type="submit">
                                    <i class="fas fa-check"></i>
                                </button>
                                @else
                                <input class="text-center form-control form-control-sm w-25 mr-2" name="quantite" id="quantite" type="number" value="{{$item->qty}}" readonly>
                                @endif
                                </div>
                            </form>
                        </td>
                            <td class="text-center align-middle" ><h5>{{$item->price}}€</h5></td>
                            </tr>
                            @endforeach
                            @if(session()->has('reduction'))
                            <tr>
                                <td class="align-middle"><h4>Réductions</h4>
                                <div class="d-flex">
                                <h5>({{session()->get('reduction')['code']}}) {{session()->get('reduction')['pourcentage']}}%</h5>
                                <form action="{{route('coupon.delete')}}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-sm text-danger">
                                        Supprimer
                                    </button>
                                </form>
                                </td>
                                <td></td>
                                <td class="text-center align-middle"><h5>-{{session()->get('reduction')['montant']}}€</h5></td>
                            </tr>
                            @endif
                            <tr class="bg-light">
                                <td class="align-middle"><h4>Total</h4></td>
                                <td></td>
                                <td class="text-center align-middle"><h5>{{$total ?? 0}}€</h5></td>
                            </tr>
                        </tbody>
                      </table>
                      <div class="d-flex justify-content-between">
                      <form method="post" action="{{route('billets.choose')}}">
                        @csrf
                        <input type="hidden" value="non" name="supprimer">
                        <input type="hidden" value="{{session()->get('matchExiste')['dateMatch']}}" name="dateMatch">
                        <input type="hidden" value="{{session()->get('matchExiste')['court']}}" name="court">
                        <button class="btn btn-secondary" type="submit">
                            Autres billets
                        </form>
                        <form method="post" action="{{route('billets.valider')}}">
                            @csrf
                            <input type="hidden" value="{{$total}}" name="total">
                            <button class="btn btn-success" type="submit">
                                Valider l'achat
                        </form>
                      </div>
                        {{-- {{Cart::content()}}<br>
                        <p style="color: blue;">{{Cart::content()->where('id', '3')}}</p>
                        {{Cart::total() .  '€'}}<br> --}}
                    @else
                    <h5> Pas de billets dans votre panier</h5>
                    <form method="post" action="{{route('billets.choose')}}">
                        @csrf
                        <input type="hidden" value="non" name="supprimer">
                        <input type="hidden" value="{{session()->get('matchExiste')['dateMatch']}}" name="dateMatch">
                        <input type="hidden" value="{{session()->get('matchExiste')['court']}}" name="court">
                        <button class="btn btn-primary" type="submit">
                            Boutique
                    </form>
                    @endif
                </div>
                    {{-- <form action="{{route('panier.supprimer')}}" method="post">
                        @csrf
                        <input type="submit" value="Tout supprimer"><br>
                    </form>
                    <form action="{{url('add')}}" method="post">
                        @csrf
                        <input type="submit" value="Ajouter billets"><br>
                    </form>
                    </div> --}}
            </div>
        </div>
    </div>
</div>
@endsection